Services
Mati2173/Hotel-Elegance-Plaza pull request #7
Opened 2024-05-17 02:07 UTC by LautaCastillo

Se creo los archivos .html y .css, correspondientes a services, ademas se agrego una img "check.png"

2024-05-17 02:43 UTC, Mati2173 requested changes

2024-05-17 02:43 UTC, Mati2173 commented on services.html
La etiqueta `<head>` no se debe utilizar de esta manera (linea 27), ya que es la primera de las dos partes en que se estructura un documento HTML, donde se pone información sobre el documento, como el título, metadatos, enlaces a scripts y hojas de estilos.

2024-05-17 02:43 UTC, Mati2173 commented on css/services.css
En cuanto a los estilos de las `cards`, cambiar el texto del título a blanco y que esté alineado a la izquierda en vez de al centro, para que se parezca al diseño original y no el del prototipo.

2024-05-18 02:38 UTC, Mati2173 approved these changes

2024-05-18 02:42 UTC, devinaxo approved these changes
Todo bn 👍

2024-05-18 02:52 UTC, merged